// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Pooler URL (Transaction pooler, port 6543) — used by the app and Vercel
    url: process.env["DATABASE_URL"],
    // Direct URL — used by prisma db push / migrate only
    directUrl: process.env["DIRECT_URL"],
  },
});
